Reproducible Research: Peer Assessment 1
================================================
### Loading and processing the data
unzip(zipfile="~/Downloads/repdata-data-activity.zip")

### What is mean total number of steps taken per day?
```{r}
### Load in the data
data <- read.csv("~/activity.csv")
library(ggplot2)
# For this part of the assignment, you can ignore the missing values in the dataset.
# Calculate the total number of steps taken per day
total.steps <- tapply(data$steps, data$date, FUN=sum, na.rm=TRUE)
qplot(total.steps, binwidth=1000, xlab="total number of steps taken each day")
# Calculate and report the mean and median of the total number of steps taken per day
mean(total.steps, na.rm=TRUE)
median(total.steps, na.rm=TRUE)
```

### What is the average daily activity pattern?
```{r}
library(ggplot2)
# Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
averages <- aggregate(x=list(steps=data$steps), by=list(interval=data$interval),
                      FUN=mean, na.rm=TRUE)
ggplot(data=averages, aes(x=interval, y=steps)) +
  geom_line() +
  xlab("5-minute interval") +
  ylab("average number of steps taken")
# Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
averages[which.max(averages$steps),]
```

### Imputing missing values
```{r}
# Calculate and report the total number of missing values in the dataset 
missing <- is.na(data$steps)
# How many missing
table(missing)
# Replace each missing value with the mean value of its 5-minute interval
fill.value <- function(steps, interval) {
  filled <- NA
  if (!is.na(steps))
    filled <- c(steps)
  else
    filled <- (averages[averages$interval==interval, "steps"])
  return(filled)
}
filled.data <- data
filled.data$steps <- mapply(fill.value, filled.data$steps, filled.data$interval)

head(filled.data)
total.steps <- tapply(filled.data$steps, filled.data$date, FUN=sum)
qplot(total.steps, binwidth=1000, xlab="total number of steps taken each day")
mean(total.steps)
median(total.steps)
```

### Are there differences in activity patterns between weekdays and weekends?

```{r}
# Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.
filled.data$date <- as.Date(filled.data$date)
filled.data$day <- factor(format(filled.data$date, "%A"))
levels(filled.data$day)
levels(filled.data$day) <- list(weekday = c("segunda", "terça",
                                             "quarta", 
                                             "quinta", "sexta"),
                                 weekend = c("sabado", "domingo"))
levels(filled.data$day)
table(filled.data$day)

# Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis)
averages <- aggregate(steps ~ interval + day, data=filled.data, mean)
ggplot(averages, aes(interval, steps)) + geom_line() + facet_grid(day ~ .) +
  xlab("5-minute interval") + ylab("Number of steps")
```